version = 5.1.0
archive_dir = /etc/letsencrypt/archive/goivondautu.delitech.vn
cert = /etc/letsencrypt/live/goivondautu.delitech.vn/cert.pem
privkey = /etc/letsencrypt/live/goivondautu.delitech.vn/privkey.pem
chain = /etc/letsencrypt/live/goivondautu.delitech.vn/chain.pem
fullchain = /etc/letsencrypt/live/goivondautu.delitech.vn/fullchain.pem
[renewalparams]
account = 460ed2d6ac37d0b7949e090ac81ddc84
authenticator = webroot
webroot_path = /var/www/certbot,
server = https://acme-v02.api.letsencrypt.org/directory
key_type = ecdsa
[[webroot_map]]
goivondautu.delitech.vn = /var/www/certbot
[acme_renewal_info]
ari_retry_after = 2025-11-29T08:34:01
